### ISSUE TITLE
Mac M1 - too many open files

### ISSUE THREAD

**Issue by DnOberon** [CrowdStrike/ivan#6]
Seeing this error constantly as i try to run the latest version

```
"level":"fatal","msg":"open /var/folders/q0/{some random string of numbers I took out}/T: too many open files","time":"2023-02-17T15:41:54Z"}
```

Any ideas? Previous version does not have this issue

**Comment by cnighojkar** [comment]
i too faced the same issue , and found that this error comes for the image which has high number of vulnarabilities.

**Comment by DnOberon** [comment]
> i too faced the same issue , and found that this error comes for the image which has high number of vulnerabilities.

Except that when I ran an older version of the tool, it reported no vulnerabilities. So not sure that's the case in my case.

**Comment by golnaraghi** [comment]
I am facing the same issue on EL8. Running the latest version(0.3.0) most of the times results in 
`{"level":"fatal","msg":"open /tmp: too many open files","time":"2023-03-27T20:52:45Z"}`.
However, the older version of the tool seems to work. Also, comparing the outputs of latest version (when it does work) and the older version, seems like they report different vulnerabilities.

**Comment by redhatrises** [comment]
Looks to be fixed in the latest release. Please re-open if not.
